PROJECT = onechat
DEPS = cowboy jiffy emysql etoml lager eredis
dep_emysql = git https://github.com/FlowerWrong/Emysql.git master
dep_eredis = git https://github.com/FlowerWrong/eredis.git master
include erlang.mk
